name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tdnbbb536/react-test-up -f ./client/Dockerfile.dev ./client # test only client project here
      - run: docker run -e CI=true tdnbbb536/react-test-up npm test # test only client project here.

      - run: docker build -t tdnbbb536/multi-client-up ./client
      - run: docker build -t tdnbbb536/multi-nginx-up ./nginx
      - run: docker build -t tdnbbb536/multi-server-up ./server
      - run: docker build -t tdnbbb536/multi-worker-up ./worker

      - run: docker push tdnbbb536/multi-client-up
      - run: docker push tdnbbb536/multi-nginx-up
      - run: docker push tdnbbb536/multi-server-up
      - run: docker push tdnbbb536/multi-worker-up

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
